-- [VIII] Sequence 순차번호 생성기, 대부분 인위적인 PK(PRIMARY KEY) 사용 용도

DROP SEQUENCE FRIEND_SEQ;

CREATE SEQUENCE FRIEND_SEQ
    START WITH 1    -- 1부터 시작
    INCREMENT BY 1  -- 1씩 증가
    MAXVALUE 9999   -- 최대값
    MINVALUE 1      -- 최소값
    NOCACHE        
    NOCYCLE;
    
SELECT FRIEND_SEQ.NEXTVAL -- 다음 순차번호
    FROM DUAL;

SELECT FRIEND_SEQ.CURRVAL -- 시퀀스의 현재 값
    FROM DUAL;

DROP SEQUENCE FRIEND_SEQ;

CREATE SEQUENCE FRIEND_SQ MAXVALUE 9999 NOCACHE NOCYCLE;

DROP TABLE FRIEND;

CREATE TABLE FRIEND (
    NUM NUMBER(4) PRIMARY KEY, -- 시퀀스 이용
    NAME VARCHAR2(30) NOT NULL,
    TEL  VARCHAR2(20) UNIQUE, -- UUNIQUE : 유일한 값, NULL 허용
    ADDRESS VARCHAR2(250),
    LAST_MODIFIED DATE DEFAULT SYSDATE -- 최종 수정일
);


INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
       VALUES (FRIEND_SQ.NEXTVAL, '홍길동', NULL, '서울시 서대문구'); -- 몇번
       

--INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
       --VALUES (FRIEND_SQ.NEXTVAL, NULL, '010-9999-9999', '서울시 마포구'); --에러 (NOT NULL)

INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
       VALUES (FRIEND_SQ.NEXTVAL, '김길동', '010-9999-9999','서울시 마포구');

--INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
       --VALUES (FRIEND_SQ.NEXTVAL, '신길동', '010-9999-9999','서울시 영등포포구'); --에러 (unique)

INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
       VALUES (FRIEND_SQ.NEXTVAL, '진길동', '010-8888-8888', '수원시 영통구');

SELECT * FROM FRIEND;

-- ex. 초기값 101부터 최대값 999,999까지 1씩 증가하는 test_seq 시퀀스를 생성하고 시퀀스 수를 사용
CREATE SEQUENCE TEST_SEQ
    START WITH 101
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;

SELECT TEST_SEQ.NEXTVAL -- 1씩 증가
    FROM DUAL;

SELECT TEST_SEQ.CURRVAL -- 현재 몇인지 확인
    FROM DUAL;


DROP SEQUENCE MEMBER_SEQ;
DROP TABLE MEMBER_LEVEL;
DROP TABLE MEMBER;

CREATE TABLE MEMBER_LEVEL (
    LEVELNO NUMBER(2),
    LEVELNAME VARCHAR2(50) NOT NULL,
    PRIMARY KEY (LEVELNO)
);

CREATE TABLE MEMBER (
    mNO    NUMBER(2),
    mNAME  VARCHAR2(50) NOT NULL,
    mPW    VARCHAR2(8),
    mEMAIL VARCHAR2(100),
    mPOINT NUMBER(4) CHECK (mPOINT>=0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(2) NOT NULL,
    FOREIGN KEY (LEVELNO) REFERENCES MEMBER_LEVEL (LEVELNO)
);

CREATE SEQUENCE MEMBER_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCACHE
    NOCYCLE;

INSERT INTO MEMBER_LEVEL VALUES (-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES (0, '일반고객');
INSERT INTO MEMBER_LEVEL VALUES (1, '실버고객');
INSERT INTO MEMBER_LEVEL VALUES (2, '골드고객');

INSERT INTO MEMBER (mNO,mNAME,mPW,mEMAIL,mPOINT,mRDATE,LEVELNO)
    VALUES (MEMBER_SEQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, '22/03/10', 0);

INSERT INTO MEMBER (mNO,mNAME,mPW,mEMAIL,mPOINT,mRDATE,LEVELNO)
    VALUES (MEMBER_SEQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, '22/04/01', 1);

SELECT mNO "mNO", mNAME "mNAME", TO_CHAR (mRDATE, 'YYYY-MM-DD')"mRDATE", 
       mEMAIL "mEMAIL", mPOINT "point", LEVELNAME "levelname"
    FROM MEMBER_LEVEL L, MEMBER M
    WHERE L.LEVELNO = M.LEVELNO;