-- 쇼핑몰 설계
DROP TABLE CART;
DROP TABLE ORDERDETAIL;
DROP TABLE ORDERS;
DROP TABLE MEMBER;
DROP TABLE PRODUCT;


CREATE TABLE MEMBER (
    mID    VARCHAR2(50) NOT NULL,
    mNAME  VARCHAR2(50) NOT NULL,
    mADDR  VARCHAR2(200)NOT NULL,
    mTEL   VARCHAR2(50) NOT NULL,
    mEMAIL VARCHAR2(50) NOT NULL,
    PRIMARY KEY (mID)
);

CREATE TABLE PRODUCT (
    pCODE VARCHAR2(50) NOT NULL,
    PNAME VARCHAR2(50) NOT NULL,
    PRICE NUMBER(4) NOT NULL,
    pSTOCK NUMBER(3),
    PRIMARY KEY (pCODE)
);

DROP SEQUENCE CART_SEQ;
CREATE SEQUENCE CART_SEQ
    MAXVALUE 9999999999
    NOCACHE;

CREATE TABLE CART (
    cNO   NUMBER(9) NOT NULL,
    mID   VARCHAR2(50) NOT NULL,
    pCODE VARCHAR2(50) NOT NULL,
    QTY1  NUMBER(4),
    COST1 NUMBER(5),
    PRIMARY KEY (cNO),
    FOREIGN KEY (mID) REFERENCES MEMBER (mID),
    FOREIGN KEY (pCODE) REFERENCES PRODUCT (pCODE)
);

DROP SEQUENCE ORDERS_SEQ;
CREATE SEQUENCE ORDERS_SEQ
    MAXVALUE 9999999999
    NOCACHE NOCYCLE;

CREATE TABLE ORDERS (
    oNO NUMBER (9) NOT NULL,
    mID VARCHAR2(50) NOT NULL,
    oNAME VARCHAR2(50) NOT NULL,
    oADDR VARCHAR2(200) NOT NULL,
    oTEL VARCHAR2(50) NOT NULL,
    oDATE DATE DEFAULT SYSDATE,
    PRIMARY KEY (oNO),
    FOREIGN KEY (mID) REFERENCES MEMBER (mID)
);

DROP SEQUENCE ORDERDETAIL_SEQ;
CREATE SEQUENCE ORDERDETAIL_SEQ
    MAXVALUE 9999999999
    NOCACHE NOCYCLE;
    
CREATE TABLE ORDERDETAIL (
    odNO  NUMBER(9) NOT NULL,
    pCODE VARCHAR2(50) NOT NULL,
    QTY   NUMBER(4),
    COST  NUMBER(5),
    PRIMARY KEY (odNO),
    FOREIGN KEY (pCODE) REFERENCES PRODUCT (pCODE)
);

INSERT INTO MEMBER VALUES ('abc', '홍길동', '서울시 서대문구 대현동', '010-9999-9999',
        'hong@hong.com');

INSERT INTO  PRODUCT VALUES ('A1', '맥주', 3000, 3);
INSERT INTO  PRODUCT VALUES ('B1', '땅콩', 3000, 1);
INSERT INTO  PRODUCT VALUES ('C1', '소독약', 7000, 1);
INSERT INTO  PRODUCT VALUES ('A2', '마스크', 200, 20);
INSERT INTO  PRODUCT VALUES ('B2', '오징어', 5000, 2);
  
INSERT INTO ORDERS VALUES (
    TO_CHAR(SYSDATE,'YYMMDD')||TRIM(TO_CHAR (ORDERS_SEQ.NEXTVAL,'000')), 
    'abc','홍길동','서울시 서대문구 대현동', '010-9999-9999');
    
INSERT INTO CART VALUES (CART_SEQ.NEXTVAL, 'abc', 'A1', 3,
        (select price from product where pCODE = 'A1')*2);
        
INSERT INTO ORDERDETAIL VALUES (
  TO_CHAR(SYSDATE, 'YYMMDD') || TRIM (TO_CHAR (ORDERS_SEQ.NEXTVAL,'000')),
  'A1', 3, (SELECT PRICE FROM PRODUCT WHERE pCODE='A1')*3);
 
INSERT INTO ORDERDETAIL VALUES (
  TO_CHAR(SYSDATE, 'YYMMDD') || TRIM (TO_CHAR (ORDERS_SEQ.NEXTVAL,'000')),
  'B1', 1, (SELECT PRICE FROM PRODUCT WHERE pCODE='B1')*1); 

UPDATE PRODUCT
    SET pSTOCK = pSTOCK -3
    WHERE pCODE = 'A1';

SELECT odNO 주문번호, M.mID 고객번호, oNAME 배송받을분, oADDR 배송주소, oTEL 배송지전화,
       p.pCODE 상품코드, P.pNAME 상품명, PRICE 단가, QTY 수량, COST 금액
    FROM MEMBER M, ORDERS S, PRODUCT P, ORDERDETAIL L
    WHERE M.mID = S.mID AND P.pCODE = L.pCODE;

SELECT p.pCODE 상품코드, P.pNAME 상품명, PRICE 단가, QTY 수량, O.COST 금액
    FROM PRODUCT P, ORDERDETAIL O
    WHERE P.pCODE = O.pCODE;
    
SELECT * FROM MEMBER;
SELECT * FROM PRODUCT;
SELECT * FROM ORDERS;
SELECT * FROM ORDERDETAIL;
SELECT * FROM CART;