-- ex2_oracle
SELECT * FROM EMP;

-- ex3_dept
SELECT * FROM DEPT;
SELECT * FROM EMP WHERE DEPTNO LIKE '%'||'10';

-- ex4 example
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, E.DEPTNO, LOC 
    FROM EMP E, DEPT D 
    WHERE E.DEPTNO=D.DEPTNO AND ENAME LIKE '%'||UPPER('')||'%';