--  CUSTOMER QUERY
-- 0. 레벨 이름들 검색
SELECT  LEVELNAME FROM CUS_LEVEL;
SELECT * FROM CUSTOMER;
-- 1. 회원가입 (고객전화와 고객이름은 입력받아 INSERT)
INSERT INTO CUSTOMER VALUES (CUS_NO_SQ.NEXTVAL, '홍길동',
    (SELECT PHONE FROM CUSTOMER WHERE CNAME ='홍길동'), 1000,0,1);



INSERT INTO Person VALUES (PERSON_NO_SQ.NEXTVAL, '홍길동',
    (SELECT JNO FROM JOB WHERE JNAME ='배우'), 81,83,85);






